# Import libraries and prepare data

In [1]:
import os
import pandas as pd
import numpy as np
import plotly.express as px
import plotly.graph_objects as go

In [2]:
# get the path to the data, not in the same location as the jupyter notebook
pathName = os.path.abspath(os.getcwd()) + "\\city-of-toronto-data\\"

fn_turn_restrict1718 = r"i0456_king_st_tmc_turn_restrictions2017_2018.csv"
fn_turn_restrict1923 = r"i0456_king_st_tmc_turn_restrictions2019_2023.csv"
fn_intersections = r"intersections_10-20.csv"

# create dataframes from csv
df_turn_restrict1718 = pd.read_csv(pathName + fn_turn_restrict1718, parse_dates=["dt_hourly"])
df_turn_restrict1923 = pd.read_csv(pathName + fn_turn_restrict1923, parse_dates=["dt_hourly"])
df_intersections = pd.read_csv(pathName + fn_intersections)

In [3]:
# set dtypes
df_turn_restrict1718['e_thru_vol'] = df_turn_restrict1718['e_thru_vol'].apply(np.int64)
df_turn_restrict1923['e_left_vol'] = df_turn_restrict1923['e_left_vol'].astype('Int64')
df_turn_restrict1923['w_right_vol'] = df_turn_restrict1923['w_right_vol'].astype('Int64')

# merge to get intersection name
df_2017_2018 = pd.merge(df_turn_restrict1718, df_intersections[["intersection_uid", "intersection_name"]], on="intersection_uid")
df_2019_2023 = pd.merge(df_turn_restrict1923, df_intersections[["intersection_uid", "intersection_name"]], on="intersection_uid")

# create date and hour columns
df_2017_2018["date"] = df_2017_2018["dt_hourly"].apply(lambda x: x.date())
df_2017_2018["hour"] = df_2017_2018["dt_hourly"].apply(lambda x: x.hour)
df_2019_2023["date"] = df_2019_2023["dt_hourly"].apply(lambda x: x.date())
df_2019_2023["hour"] = df_2019_2023["dt_hourly"].apply(lambda x: x.hour)

## Intersection Variables

In [4]:
titles_dict = {
    10 : "King / Bathurst, EW Traffic Volumes",
    11 : "King / Portland, EW Traffic Volumes",
    12 : "King / Spadina, EW Traffic Volumes",
    13 : "King / Peter, EW Traffic Volumes",
    14 : "King / Simcoe, EW Traffic Volumes",
    15 : "King / University, EW Traffic Volumes",
    16 : "King / York, EW Traffic Volumes",
    17 : "King / Bay, EW Traffic Volumes",
    18 : "King / Yonge, EW Traffic Volumes",
    19 : "King / Church, EW Traffic Volumes",
    20 : "King / Jarvis, EW Traffic Volumes"
}

In [5]:
intersections_dict = {
    10 : "King / Bathurst",
    11 : "King / Portland",
    12 : "King / Spadina",
    13 : "King / Peter",
    14 : "King / Simcoe",
    15 : "King / University",
    16 : "King / York",
    17 : "King / Bay",
    18 : "King / Yonge",
    19 : "King / Church",
    20 : "King / Jarvis"
}

In [6]:
labels_dict = {
    10 : { # King / Bathurst
        "e_thru_vol" : "E Thru Traffic *", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic *", 
        "w_left_vol": "W Left Turns", 
        "w_right_vol" : "W Right Turns"
        },
    11 : { # King / Portland
        "e_thru_vol" : "E Thru Traffic *", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic *", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        },
    12 : { # King / Spadina
        "e_thru_vol" : "E Thru Traffic *", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic *", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        },
    13 : { # King / Peter
        "e_thru_vol" : "E Thru Traffic *", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic *", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        },
    14 : { # King / Simcoe
        "e_thru_vol" : "E Thru Traffic", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic", 
        "w_left_vol": "W Left Turns", 
        "w_right_vol" : "W Right Turns"
        },
    15 : { # King / University
        "e_thru_vol" : "E Thru Traffic *", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic *", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        },
    16 : { # King / York
        "e_thru_vol" : "E Thru Traffic", 
        "e_left_vol" : "E Left Turns", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        },
    17 : { # King / Bay
        "e_thru_vol" : "E Thru Traffic", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        },
    18 : { # King / Yonge
        "e_thru_vol" : "E Thru Traffic *", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic *", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        },
    19 : { # King / Church
        "e_thru_vol" : "E Thru Traffic *", 
        "e_left_vol" : "E Left Turns *", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic *", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        },
    20 : { # King / Jarvis
        "e_thru_vol" : "E Thru Traffic *", 
        "e_left_vol" : "E Left Turns", 
        "e_right_vol" : "E Right Turns", 
        "w_thru_vol" : "W Thru Traffic *", 
        "w_left_vol": "W Left Turns *", 
        "w_right_vol" : "W Right Turns"
        }
}

## Filtering Data

### Taxi Mask

In [7]:
# Taxi Masks
TaxiMask1 = (df_2017_2018["hour"] >= 5) & (df_2017_2018["hour"] < 22)
df_2017_2018_nt = df_2017_2018[TaxiMask1].copy()

TaxiMask2 = (df_2019_2023["hour"] >= 5) & (df_2019_2023["hour"] < 22)
df_2019_2023_nt = df_2019_2023[TaxiMask2].copy()

In [8]:
# Concatenating the two dataframes
df_all_nt = pd.concat([df_2017_2018_nt, df_2019_2023_nt])
df_all_nt

,intersection_uid,dt_hourly,e_thru_vol,e_left_vol,e_right_vol,w_thru_vol,w_left_vol,w_right_vol,intersection_name,date,hour
0,10,2017-10-03 14:00:00,262,44,51,203,111,47,King / Bathurst,2017-10-03,14
1,10,2017-10-03 15:00:00,365,73,57,222,127,55,King / Bathurst,2017-10-03,15
2,10,2017-10-03 16:00:00,381,57,57,222,153,49,King / Bathurst,2017-10-03,16
3,10,2017-10-03 17:00:00,389,76,46,265,154,51,King / Bathurst,2017-10-03,17
4,10,2017-10-03 18:00:00,314,53,48,333,164,70,King / Bathurst,2017-10-03,18
...,...,...,...,...,...,...,...,...,...,...,...
266629,20,2023-02-03 17:00:00,104,62,9,10,2,54,King / Jarvis,2023-02-03,17
266630,20,2023-02-03 18:00:00,94,63,8,14,0,61,King / Jarvis,2023-02-03,18
266631,20,2023-02-03 19:00:00,41,241,3,10,0,37,King / Jarvis,2023-02-03,19
266632,20,2023-02-03 20:00:00,37,179,2,6,0,44,King / Jarvis,2023-02-03,20
266633,20,2023-02-03 21:00:00,18,155,4,22,0,58,King / Jarvis,2023-02-03,21

## Aggregation

In [9]:
allmvmt = ["e_thru_vol", "e_left_vol", "e_right_vol", "w_thru_vol", "w_left_vol", "w_right_vol"]

In [18]:
resultsall = df_all_nt[["date", "intersection_uid", "intersection_name"] + allmvmt].groupby(['date', 'intersection_uid', 'intersection_name']).aggregate("sum")
resultsalli = resultsall.reset_index()
resultsalli["datet"] = pd.to_datetime(resultsalli["date"])

## additional date-related columns
# resultsalli["year"] = resultsalli["datet"].dt.year
# resultsalli["doy"] = resultsalli["datet"].dt.dayofyear
# resultsalli["date"] = resultsalli["datet"].dt.date
resultsalli[resultsalli["intersection_uid"] == 10]

,date,intersection_uid,intersection_name,e_thru_vol,e_left_vol,e_right_vol,w_thru_vol,w_left_vol,w_right_vol,datet
0,2017-10-03,10,King / Bathurst,2386,453,457,1967,1075,467,2017-10-03
1,2017-10-04,10,King / Bathurst,4582,823,851,4715,2459,898,2017-10-04
3,2017-10-05,10,King / Bathurst,4733,830,804,4636,2299,863,2017-10-05
5,2017-10-06,10,King / Bathurst,4497,785,969,4505,2416,1030,2017-10-06
7,2017-10-10,10,King / Bathurst,4201,721,928,4543,2214,918,2017-10-10
...,...,...,...,...,...,...,...,...,...,...
11746,2023-05-27,10,King / Bathurst,964,43,1202,404,3213,1520,2023-05-27
11751,2023-05-28,10,King / Bathurst,434,31,722,336,2811,1280,2023-05-28
11756,2023-05-29,10,King / Bathurst,412,28,606,270,3261,1305,2023-05-29
11761,2023-05-30,10,King / Bathurst,583,44,810,362,3538,1646,2023-05-30
11766,2023-05-31,10,King / Bathurst,555,42,762,344,3509,1537,2023-05-31

## Plotly Dash

In [20]:
# from jupyter_dash import JupyterDash
from dash import Dash, dcc, html, Input, Output#, jupyter_dash

# Build App
app = Dash("King")
app.layout = html.Div([
    # html.H1("King St JupyterDash Test"),
    dcc.Graph(id='graph'),
    html.Label([
        "Intersection",
        dcc.Dropdown(
            id='intersection-dropdown', clearable=False,
            value='10', options=[
                {'label': intersections_dict[i], 'value': i}
                for i in intersections_dict
            ])
    ]),
])

# Define callback to update graph
@app.callback(
    Output('graph', 'figure'),
    [Input("intersection-dropdown", "value")]
)

def update_figure(input):
    r = resultsalli[resultsalli["intersection_uid"] == input]
    r = r.reset_index()
    r["datet"] = pd.to_datetime(r["date"])

    fig = px.scatter(
        r,
        x="datet", 
        y=["e_thru_vol", "e_left_vol", "e_right_vol", "w_thru_vol", "w_left_vol", "w_right_vol"],
        labels={
            "datet" : "Date", 
            "value" : "Traffic Volume", 
            "variable" : "Movement"}, 
        trendline="lowess", 
        trendline_options=dict(frac=0.3),
        height=600,
        title=titles_dict[input])
    
    fig.for_each_trace(lambda t: t.update(name = labels_dict[input][t.name], 
                                          legendgroup = labels_dict[input][t.name], 
                                          hovertemplate = t.hovertemplate.replace(t.name, labels_dict[input][t.name])))

    fig.update_xaxes(dtick="M1", tickformat="%b\n%Y", ticklabelmode="period")

    return fig

# Run app and display result inline in the notebook
app.run_server(mode="inline", port=8051, use_reloader=False)